version: '3.6'

services:
  api:
    image: baxter40/exampleapi:1.1
    build:
      context: .
      dockerfile: ./API/Dockerfile
    container_name: example-dotnet-api
    ports:
      - "30425:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - /var/lib/Database/ExampleDocker/Prod/:/Database/
  frontend:
    image: baxter40/examplefrontend:1.1
    build:
      context: .
      dockerfile: ./FrontEnd/Dockerfile
    container_name: example-angular-ui
    ports:
      - "4301:80"
